/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Vss
{
  public enum TContentKind
  {
    Folder = 0,
    BinaryFile = 1,
    Weibo = 2,
    ShortMessage = 3,
    Picture = 4,
    Music = 5,
    Movie = 6,
    Email = 7,
  }
}
