/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Vss
{
  public enum TLoginResult
  {
    SUCCESS = 0,
    FAIL_NOAPPPRIV = 1,
    FAIL_WRONGPSW = 2,
  }
}
